#!/usr/bin/env perl

use strict;
use warnings;
use Getopt::Long;
use Git::Filter::Credentials;

my $unreplace = '';
my $config_filename = '';
GetOptions(
    'config=s' => \$config_filename,
    'unreplace' => \$unreplace);
my %options = ();
if ($config_filename ne '') {
    $options{CONFIG_FILENAME} = $config_filename;
}
my $filter = Git::Filter::Credentials->new(%options);

while (<STDIN>) {
    print $unreplace ? $filter->unreplace : $filter->replace;
}
